

package org.jetbrains.kotlin.formver.plugin.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.formver.plugin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("formver.compiler-plugin/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class PhasedDiagnosticTestGenerated extends AbstractPhasedDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("formver.compiler-plugin/testData/diagnostics/expensive_verification")
  @TestDataPath("$PROJECT_ROOT")
  public class Expensive_verification {
    @Test
    public void testAllFilesPresentInExpensive_verification() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/expensive_verification"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("backing_field_getters.kt")
    public void testBacking_field_getters() {
      runTest("formver.compiler-plugin/testData/diagnostics/expensive_verification/backing_field_getters.kt");
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms")
    @TestDataPath("$PROJECT_ROOT")
    public class Algorithms {
      @Test
      public void testAllFilesPresentInAlgorithms() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("binary_search.kt")
      public void testBinary_search() {
        runTest("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms/binary_search.kt");
      }

      @Test
      @TestMetadata("insertion_sort_array.kt")
      public void testInsertion_sort_array() {
        runTest("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms/insertion_sort_array.kt");
      }

      @Test
      @TestMetadata("insertion_sort_functional.kt")
      public void testInsertion_sort_functional() {
        runTest("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms/insertion_sort_functional.kt");
      }

      @Test
      @TestMetadata("insertion_sort_linked.kt")
      public void testInsertion_sort_linked() {
        runTest("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms/insertion_sort_linked.kt");
      }

      @Test
      @TestMetadata("insertion_sort_linked_contents.kt")
      public void testInsertion_sort_linked_contents() {
        runTest("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms/insertion_sort_linked_contents.kt");
      }

      @Test
      @TestMetadata("levenshtein.kt")
      public void testLevenshtein() {
        runTest("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms/levenshtein.kt");
      }

      @Test
      @TestMetadata("max_character.kt")
      public void testMax_character() {
        runTest("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms/max_character.kt");
      }

      @Test
      @TestMetadata("merge_sort_of_string.kt")
      public void testMerge_sort_of_string() {
        runTest("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms/merge_sort_of_string.kt");
      }

      @Test
      @TestMetadata("permutation_array.kt")
      public void testPermutation_array() {
        runTest("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms/permutation_array.kt");
      }

      @Test
      @TestMetadata("quick_sort_of_string.kt")
      public void testQuick_sort_of_string() {
        runTest("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms/quick_sort_of_string.kt");
      }

      @Test
      @TestMetadata("reverse_linked.kt")
      public void testReverse_linked() {
        runTest("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms/reverse_linked.kt");
      }

      @Test
      @TestMetadata("z_function.kt")
      public void testZ_function() {
        runTest("formver.compiler-plugin/testData/diagnostics/expensive_verification/algorithms/z_function.kt");
      }
    }
  }

  @Nested
  @TestMetadata("formver.compiler-plugin/testData/diagnostics/stdlib")
  @TestDataPath("$PROJECT_ROOT")
  public class Stdlib {
    @Test
    public void testAllFilesPresentInStdlib() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/stdlib"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("stdlib_replacement_tests.kt")
    public void testStdlib_replacement_tests() {
      runTest("formver.compiler-plugin/testData/diagnostics/stdlib/stdlib_replacement_tests.kt");
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/stdlib/array")
    @TestDataPath("$PROJECT_ROOT")
    public class Array {
      @Test
      public void testAllFilesPresentInArray() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/stdlib/array"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("int_array.kt")
      public void testInt_array() {
        runTest("formver.compiler-plugin/testData/diagnostics/stdlib/array/int_array.kt");
      }

      @Test
      @TestMetadata("int_array_elements.kt")
      public void testInt_array_elements() {
        runTest("formver.compiler-plugin/testData/diagnostics/stdlib/array/int_array_elements.kt");
      }

      @Test
      @TestMetadata("int_array_init.kt")
      public void testInt_array_init() {
        runTest("formver.compiler-plugin/testData/diagnostics/stdlib/array/int_array_init.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/stdlib/comparisons")
    @TestDataPath("$PROJECT_ROOT")
    public class Comparisons {
      @Test
      public void testAllFilesPresentInComparisons() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/stdlib/comparisons"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("min_max_of.kt")
      public void testMin_max_of() {
        runTest("formver.compiler-plugin/testData/diagnostics/stdlib/comparisons/min_max_of.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/stdlib/list")
    @TestDataPath("$PROJECT_ROOT")
    public class List {
      @Test
      public void testAllFilesPresentInList() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/stdlib/list"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("binary_search.kt")
      public void testBinary_search() {
        runTest("formver.compiler-plugin/testData/diagnostics/stdlib/list/binary_search.kt");
      }

      @Test
      @TestMetadata("custom_list.kt")
      public void testCustom_list() {
        runTest("formver.compiler-plugin/testData/diagnostics/stdlib/list/custom_list.kt");
      }

      @Test
      @TestMetadata("list.kt")
      public void testList() {
        runTest("formver.compiler-plugin/testData/diagnostics/stdlib/list/list.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/stdlib/string")
    @TestDataPath("$PROJECT_ROOT")
    public class String {
      @Test
      public void testAllFilesPresentInString() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/stdlib/string"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("char_sequence.kt")
      public void testChar_sequence() {
        runTest("formver.compiler-plugin/testData/diagnostics/stdlib/string/char_sequence.kt");
      }

      @Test
      @TestMetadata("chars.kt")
      public void testChars() {
        runTest("formver.compiler-plugin/testData/diagnostics/stdlib/string/chars.kt");
      }

      @Test
      @TestMetadata("strings.kt")
      public void testStrings() {
        runTest("formver.compiler-plugin/testData/diagnostics/stdlib/string/strings.kt");
      }

      @Test
      @TestMetadata("templates.kt")
      public void testTemplates() {
        runTest("formver.compiler-plugin/testData/diagnostics/stdlib/string/templates.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/stdlib/string_builder")
    @TestDataPath("$PROJECT_ROOT")
    public class String_builder {
      @Test
      public void testAllFilesPresentInString_builder() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/stdlib/string_builder"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("implicit_receiver.kt")
      public void testImplicit_receiver() {
        runTest("formver.compiler-plugin/testData/diagnostics/stdlib/string_builder/implicit_receiver.kt");
      }

      @Test
      @TestMetadata("string_builder.kt")
      public void testString_builder() {
        runTest("formver.compiler-plugin/testData/diagnostics/stdlib/string_builder/string_builder.kt");
      }
    }
  }

  @Nested
  @TestMetadata("formver.compiler-plugin/testData/diagnostics/uniqueness_checker")
  @TestDataPath("$PROJECT_ROOT")
  public class Uniqueness_checker {
    @Test
    @TestMetadata("accessor_receiver.kt")
    public void testAccessor_receiver() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/accessor_receiver.kt");
    }

    @Test
    @TestMetadata("aliasing.kt")
    public void testAliasing() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/aliasing.kt");
    }

    @Test
    public void testAllFilesPresentInUniqueness_checker() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/uniqueness_checker"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("annotations.kt")
    public void testAnnotations() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/annotations.kt");
    }

    @Test
    @TestMetadata("assign_local.kt")
    public void testAssign_local() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/assign_local.kt");
    }

    @Test
    @TestMetadata("assign_property.kt")
    public void testAssign_property() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/assign_property.kt");
    }

    @Test
    @TestMetadata("break.kt")
    public void testBreak() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/break.kt");
    }

    @Test
    @TestMetadata("call.kt")
    public void testCall() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/call.kt");
    }

    @Test
    @TestMetadata("capture_accepted.kt")
    public void testCapture_accepted() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/capture_accepted.kt");
    }

    @Test
    @TestMetadata("capture_rejected.kt")
    public void testCapture_rejected() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/capture_rejected.kt");
    }

    @Test
    @TestMetadata("conditional_fresh.kt")
    public void testConditional_fresh() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/conditional_fresh.kt");
    }

    @Test
    @TestMetadata("consistency.kt")
    public void testConsistency() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/consistency.kt");
    }

    @Test
    @TestMetadata("construction_escape.kt")
    public void testConstruction_escape() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/construction_escape.kt");
    }

    @Test
    @TestMetadata("constructor.kt")
    public void testConstructor() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/constructor.kt");
    }

    @Test
    @TestMetadata("context.kt")
    public void testContext() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/context.kt");
    }

    @Test
    @TestMetadata("continue.kt")
    public void testContinue() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/continue.kt");
    }

    @Test
    @TestMetadata("declaration_annotations.kt")
    public void testDeclaration_annotations() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/declaration_annotations.kt");
    }

    @Test
    @TestMetadata("default_argument.kt")
    public void testDefault_argument() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/default_argument.kt");
    }

    @Test
    @TestMetadata("dump_cfg.kt")
    public void testDump_cfg() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/dump_cfg.kt");
    }

    @Test
    @TestMetadata("expect_actual.kt")
    public void testExpect_actual() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/expect_actual.kt");
    }

    @Test
    @TestMetadata("ghost.kt")
    public void testGhost() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/ghost.kt");
    }

    @Test
    @TestMetadata("int_array.kt")
    public void testInt_array() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/int_array.kt");
    }

    @Test
    @TestMetadata("lambda.kt")
    public void testLambda() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/lambda.kt");
    }

    @Test
    @TestMetadata("leak.kt")
    public void testLeak() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/leak.kt");
    }

    @Test
    @TestMetadata("list_reverse.kt")
    public void testList_reverse() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/list_reverse.kt");
    }

    @Test
    @TestMetadata("loop.kt")
    public void testLoop() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/loop.kt");
    }

    @Test
    @TestMetadata("moved_access.kt")
    public void testMoved_access() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/moved_access.kt");
    }

    @Test
    @TestMetadata("nullable.kt")
    public void testNullable() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/nullable.kt");
    }

    @Test
    @TestMetadata("operator.kt")
    public void testOperator() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/operator.kt");
    }

    @Test
    @TestMetadata("override_accepted.kt")
    public void testOverride_accepted() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/override_accepted.kt");
    }

    @Test
    @TestMetadata("override_rejected.kt")
    public void testOverride_rejected() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/override_rejected.kt");
    }

    @Test
    @TestMetadata("primitive.kt")
    public void testPrimitive() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/primitive.kt");
    }

    @Test
    @TestMetadata("pure.kt")
    public void testPure() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/pure.kt");
    }

    @Test
    @TestMetadata("pure_postconditions.kt")
    public void testPure_postconditions() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/pure_postconditions.kt");
    }

    @Test
    @TestMetadata("pure_spec.kt")
    public void testPure_spec() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/pure_spec.kt");
    }

    @Test
    @TestMetadata("receiver.kt")
    public void testReceiver() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/receiver.kt");
    }

    @Test
    @TestMetadata("return.kt")
    public void testReturn() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/return.kt");
    }

    @Test
    @TestMetadata("string_builder.kt")
    public void testString_builder() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/string_builder.kt");
    }

    @Test
    @TestMetadata("this_receiver.kt")
    public void testThis_receiver() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/this_receiver.kt");
    }

    @Test
    @TestMetadata("throw.kt")
    public void testThrow() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/throw.kt");
    }

    @Test
    @TestMetadata("try_catch.kt")
    public void testTry_catch() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/try_catch.kt");
    }

    @Test
    @TestMetadata("type_parameter_accepted.kt")
    public void testType_parameter_accepted() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/type_parameter_accepted.kt");
    }

    @Test
    @TestMetadata("type_parameter_rejected.kt")
    public void testType_parameter_rejected() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/type_parameter_rejected.kt");
    }

    @Test
    @TestMetadata("unannotated_classes.kt")
    public void testUnannotated_classes() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/unannotated_classes.kt");
    }

    @Test
    @TestMetadata("when_expression.kt")
    public void testWhen_expression() {
      runTest("formver.compiler-plugin/testData/diagnostics/uniqueness_checker/when_expression.kt");
    }
  }

  @Nested
  @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification")
  @TestDataPath("$PROJECT_ROOT")
  public class Verification {
    @Test
    public void testAllFilesPresentInVerification() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("basic.kt")
    public void testBasic() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/basic.kt");
    }

    @Test
    @TestMetadata("do_not_verify.kt")
    public void testDo_not_verify() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/do_not_verify.kt");
    }

    @Test
    @TestMetadata("extension_properties.kt")
    public void testExtension_properties() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/extension_properties.kt");
    }

    @Test
    @TestMetadata("full_viper_dump.kt")
    public void testFull_viper_dump() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/full_viper_dump.kt");
    }

    @Test
    @TestMetadata("function_object.kt")
    public void testFunction_object() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/function_object.kt");
    }

    @Test
    @TestMetadata("function_overloading.kt")
    public void testFunction_overloading() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/function_overloading.kt");
    }

    @Test
    @TestMetadata("havoc.kt")
    public void testHavoc() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/havoc.kt");
    }

    @Test
    @TestMetadata("internal_error_position.kt")
    public void testInternal_error_position() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/internal_error_position.kt");
    }

    @Test
    @TestMetadata("lambda_values.kt")
    public void testLambda_values() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/lambda_values.kt");
    }

    @Test
    @TestMetadata("local_class.kt")
    public void testLocal_class() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/local_class.kt");
    }

    @Test
    @TestMetadata("loop_predicate_invariant.kt")
    public void testLoop_predicate_invariant() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/loop_predicate_invariant.kt");
    }

    @Test
    @TestMetadata("loop_predicate_invariant_negative.kt")
    public void testLoop_predicate_invariant_negative() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/loop_predicate_invariant_negative.kt");
    }

    @Test
    @TestMetadata("manualFolding.kt")
    public void testManualFolding() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/manualFolding.kt");
    }

    @Test
    @TestMetadata("manualFoldingNegative.kt")
    public void testManualFoldingNegative() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/manualFoldingNegative.kt");
    }

    @Test
    @TestMetadata("multiple_receivers.kt")
    public void testMultiple_receivers() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/multiple_receivers.kt");
    }

    @Test
    @TestMetadata("old.kt")
    public void testOld() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/old.kt");
    }

    @Test
    @TestMetadata("shadowing.kt")
    public void testShadowing() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/shadowing.kt");
    }

    @Test
    @TestMetadata("spec_unfolding_placement.kt")
    public void testSpec_unfolding_placement() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/spec_unfolding_placement.kt");
    }

    @Test
    @TestMetadata("top_level_properties.kt")
    public void testTop_level_properties() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/top_level_properties.kt");
    }

    @Test
    @TestMetadata("uniqueness_errors.kt")
    public void testUniqueness_errors() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/uniqueness_errors.kt");
    }

    @Test
    @TestMetadata("unit_return_type.kt")
    public void testUnit_return_type() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/unit_return_type.kt");
    }

    @Test
    @TestMetadata("unsupported_constructs.kt")
    public void testUnsupported_constructs() {
      runTest("formver.compiler-plugin/testData/diagnostics/verification/unsupported_constructs.kt");
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/classes")
    @TestDataPath("$PROJECT_ROOT")
    public class Classes {
      @Test
      @TestMetadata("acc_precondition.kt")
      public void testAcc_precondition() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/acc_precondition.kt");
      }

      @Test
      public void testAllFilesPresentInClasses() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/classes"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("construction_writes.kt")
      public void testConstruction_writes() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/construction_writes.kt");
      }

      @Test
      @TestMetadata("inheritance.kt")
      public void testInheritance() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/inheritance.kt");
      }

      @Test
      @TestMetadata("inheritance_fields.kt")
      public void testInheritance_fields() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/inheritance_fields.kt");
      }

      @Test
      @TestMetadata("interfaces.kt")
      public void testInterfaces() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/interfaces.kt");
      }

      @Test
      @TestMetadata("list_reverse.kt")
      public void testList_reverse() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/list_reverse.kt");
      }

      @Test
      @TestMetadata("manual_permissions.kt")
      public void testManual_permissions() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/manual_permissions.kt");
      }

      @Test
      @TestMetadata("manual_shared_write.kt")
      public void testManual_shared_write() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/manual_shared_write.kt");
      }

      @Test
      @TestMetadata("member_functions.kt")
      public void testMember_functions() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/member_functions.kt");
      }

      @Test
      @TestMetadata("member_this_contracts.kt")
      public void testMember_this_contracts() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/member_this_contracts.kt");
      }

      @Test
      @TestMetadata("member_this_receiver.kt")
      public void testMember_this_receiver() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/member_this_receiver.kt");
      }

      @Test
      @TestMetadata("override_contracts.kt")
      public void testOverride_contracts() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/override_contracts.kt");
      }

      @Test
      @TestMetadata("override_contracts_negative.kt")
      public void testOverride_contracts_negative() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/override_contracts_negative.kt");
      }

      @Test
      @TestMetadata("override_properties_types.kt")
      public void testOverride_properties_types() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/override_properties_types.kt");
      }

      @Test
      @TestMetadata("override_spec_of.kt")
      public void testOverride_spec_of() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/override_spec_of.kt");
      }

      @Test
      @TestMetadata("ownership_not_established.kt")
      public void testOwnership_not_established() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/ownership_not_established.kt");
      }

      @Test
      @TestMetadata("predicates.kt")
      public void testPredicates() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/predicates.kt");
      }

      @Test
      @TestMetadata("predicates_access.kt")
      public void testPredicates_access() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/predicates_access.kt");
      }

      @Test
      @TestMetadata("primary_constructors.kt")
      public void testPrimary_constructors() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/primary_constructors.kt");
      }

      @Test
      @TestMetadata("private_properties.kt")
      public void testPrivate_properties() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/private_properties.kt");
      }

      @Test
      @TestMetadata("property_accessors.kt")
      public void testProperty_accessors() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/property_accessors.kt");
      }

      @Test
      @TestMetadata("secondary_constructors.kt")
      public void testSecondary_constructors() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/secondary_constructors.kt");
      }

      @Test
      @TestMetadata("subtyping.kt")
      public void testSubtyping() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/subtyping.kt");
      }

      @Test
      @TestMetadata("unique_accessor_receiver.kt")
      public void testUnique_accessor_receiver() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/unique_accessor_receiver.kt");
      }

      @Test
      @TestMetadata("unique_borrowed_shared.kt")
      public void testUnique_borrowed_shared() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/unique_borrowed_shared.kt");
      }

      @Test
      @TestMetadata("unique_borrowed_supertype.kt")
      public void testUnique_borrowed_supertype() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/unique_borrowed_supertype.kt");
      }

      @Test
      @TestMetadata("unique_compound_assignment.kt")
      public void testUnique_compound_assignment() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/unique_compound_assignment.kt");
      }

      @Test
      @TestMetadata("unique_conditional_values.kt")
      public void testUnique_conditional_values() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/unique_conditional_values.kt");
      }

      @Test
      @TestMetadata("unique_constructors.kt")
      public void testUnique_constructors() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/unique_constructors.kt");
      }

      @Test
      @TestMetadata("unique_fields.kt")
      public void testUnique_fields() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/unique_fields.kt");
      }

      @Test
      @TestMetadata("unique_fold_state.kt")
      public void testUnique_fold_state() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/unique_fold_state.kt");
      }

      @Test
      @TestMetadata("unique_hierarchy_moves.kt")
      public void testUnique_hierarchy_moves() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/unique_hierarchy_moves.kt");
      }

      @Test
      @TestMetadata("unique_loop_framing.kt")
      public void testUnique_loop_framing() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/unique_loop_framing.kt");
      }

      @Test
      @TestMetadata("unique_loop_heads.kt")
      public void testUnique_loop_heads() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/unique_loop_heads.kt");
      }

      @Test
      @TestMetadata("unique_nullable_fold.kt")
      public void testUnique_nullable_fold() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/unique_nullable_fold.kt");
      }

      @Test
      @TestMetadata("unique_partial_moves.kt")
      public void testUnique_partial_moves() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/unique_partial_moves.kt");
      }

      @Test
      @TestMetadata("unique_receiver_loop.kt")
      public void testUnique_receiver_loop() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/unique_receiver_loop.kt");
      }

      @Test
      @TestMetadata("unique_try.kt")
      public void testUnique_try() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/unique_try.kt");
      }

      @Test
      @TestMetadata("unique_val_fields.kt")
      public void testUnique_val_fields() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/unique_val_fields.kt");
      }

      @Test
      @TestMetadata("untracked_write.kt")
      public void testUntracked_write() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/classes/untracked_write.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/contracts")
    @TestDataPath("$PROJECT_ROOT")
    public class Contracts {
      @Test
      public void testAllFilesPresentInContracts() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/contracts"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Nested
      @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative")
      @TestDataPath("$PROJECT_ROOT")
      public class Negative {
        @Test
        public void testAllFilesPresentInNegative() {
          KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative"), Pattern.compile("^(.+)\\.kt$"), null, true);
        }

        @Test
        @TestMetadata("as_type_contract.kt")
        public void testAs_type_contract() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative/as_type_contract.kt");
        }

        @Test
        @TestMetadata("cond_effects.kt")
        public void testCond_effects() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative/cond_effects.kt");
        }

        @Test
        @TestMetadata("contracts_with_receivers.kt")
        public void testContracts_with_receivers() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative/contracts_with_receivers.kt");
        }

        @Test
        @TestMetadata("is_type_contract.kt")
        public void testIs_type_contract() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative/is_type_contract.kt");
        }

        @Test
        @TestMetadata("list.kt")
        public void testList() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative/list.kt");
        }

        @Test
        @TestMetadata("returns_booleans.kt")
        public void testReturns_booleans() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative/returns_booleans.kt");
        }

        @Test
        @TestMetadata("returns_not_null.kt")
        public void testReturns_not_null() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative/returns_not_null.kt");
        }

        @Test
        @TestMetadata("returns_null.kt")
        public void testReturns_null() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative/returns_null.kt");
        }

        @Test
        @TestMetadata("spec_of_errors.kt")
        public void testSpec_of_errors() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative/spec_of_errors.kt");
        }

        @Test
        @TestMetadata("viper_verify.kt")
        public void testViper_verify() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/negative/viper_verify.kt");
        }
      }

      @Nested
      @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/contracts/positive")
      @TestDataPath("$PROJECT_ROOT")
      public class Positive {
        @Test
        public void testAllFilesPresentInPositive() {
          KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/contracts/positive"), Pattern.compile("^(.+)\\.kt$"), null, true);
        }

        @Test
        @TestMetadata("as_type_contract.kt")
        public void testAs_type_contract() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/positive/as_type_contract.kt");
        }

        @Test
        @TestMetadata("contracts_with_receivers.kt")
        public void testContracts_with_receivers() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/positive/contracts_with_receivers.kt");
        }

        @Test
        @TestMetadata("is_type_contract.kt")
        public void testIs_type_contract() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/positive/is_type_contract.kt");
        }

        @Test
        @TestMetadata("returns_booleans.kt")
        public void testReturns_booleans() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/positive/returns_booleans.kt");
        }

        @Test
        @TestMetadata("returns_null.kt")
        public void testReturns_null() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/positive/returns_null.kt");
        }

        @Test
        @TestMetadata("simple.kt")
        public void testSimple() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/positive/simple.kt");
        }

        @Test
        @TestMetadata("spec_of.kt")
        public void testSpec_of() {
          runTest("formver.compiler-plugin/testData/diagnostics/verification/contracts/positive/spec_of.kt");
        }
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/control_flow")
    @TestDataPath("$PROJECT_ROOT")
    public class Control_flow {
      @Test
      public void testAllFilesPresentInControl_flow() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/control_flow"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("exp_side_effects.kt")
      public void testExp_side_effects() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/control_flow/exp_side_effects.kt");
      }

      @Test
      @TestMetadata("for_ranges.kt")
      public void testFor_ranges() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/control_flow/for_ranges.kt");
      }

      @Test
      @TestMetadata("function_call.kt")
      public void testFunction_call() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/control_flow/function_call.kt");
      }

      @Test
      @TestMetadata("if.kt")
      public void testIf() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/control_flow/if.kt");
      }

      @Test
      @TestMetadata("loops.kt")
      public void testLoops() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/control_flow/loops.kt");
      }

      @Test
      @TestMetadata("non-local-returns.kt")
      public void testNon_local_returns() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/control_flow/non-local-returns.kt");
      }

      @Test
      @TestMetadata("recursion.kt")
      public void testRecursion() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/control_flow/recursion.kt");
      }

      @Test
      @TestMetadata("return_break_continue.kt")
      public void testReturn_break_continue() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/control_flow/return_break_continue.kt");
      }

      @Test
      @TestMetadata("throw.kt")
      public void testThrow() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/control_flow/throw.kt");
      }

      @Test
      @TestMetadata("when.kt")
      public void testWhen() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/control_flow/when.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/inlining")
    @TestDataPath("$PROJECT_ROOT")
    public class Inlining {
      @Test
      public void testAllFilesPresentInInlining() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/inlining"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("custom_run_functions.kt")
      public void testCustom_run_functions() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/inlining/custom_run_functions.kt");
      }

      @Test
      @TestMetadata("default_arguments.kt")
      public void testDefault_arguments() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/inlining/default_arguments.kt");
      }

      @Test
      @TestMetadata("inline_calls_in_specifications.kt")
      public void testInline_calls_in_specifications() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/inlining/inline_calls_in_specifications.kt");
      }

      @Test
      @TestMetadata("inline_returns.kt")
      public void testInline_returns() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/inlining/inline_returns.kt");
      }

      @Test
      @TestMetadata("inline_unique.kt")
      public void testInline_unique() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/inlining/inline_unique.kt");
      }

      @Test
      @TestMetadata("inline_unique_arguments.kt")
      public void testInline_unique_arguments() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/inlining/inline_unique_arguments.kt");
      }

      @Test
      @TestMetadata("inline_unique_jumps.kt")
      public void testInline_unique_jumps() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/inlining/inline_unique_jumps.kt");
      }

      @Test
      @TestMetadata("lambdas.kt")
      public void testLambdas() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/inlining/lambdas.kt");
      }

      @Test
      @TestMetadata("owned_writes.kt")
      public void testOwned_writes() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/inlining/owned_writes.kt");
      }

      @Test
      @TestMetadata("scoped_receivers.kt")
      public void testScoped_receivers() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/inlining/scoped_receivers.kt");
      }

      @Test
      @TestMetadata("stdlib_hof_invariants.kt")
      public void testStdlib_hof_invariants() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/inlining/stdlib_hof_invariants.kt");
      }

      @Test
      @TestMetadata("stdlib_hof_lambdas.kt")
      public void testStdlib_hof_lambdas() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/inlining/stdlib_hof_lambdas.kt");
      }

      @Test
      @TestMetadata("stdlib_hof_predicates.kt")
      public void testStdlib_hof_predicates() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/inlining/stdlib_hof_predicates.kt");
      }

      @Test
      @TestMetadata("viper_casts_while_inlining.kt")
      public void testViper_casts_while_inlining() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/inlining/viper_casts_while_inlining.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/negative")
    @TestDataPath("$PROJECT_ROOT")
    public class Negative {
      @Test
      public void testAllFilesPresentInNegative() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/negative"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("binary_tree.kt")
      public void testBinary_tree() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/negative/binary_tree.kt");
      }

      @Test
      @TestMetadata("linked_list.kt")
      public void testLinked_list() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/negative/linked_list.kt");
      }

      @Test
      @TestMetadata("try_catch.kt")
      public void testTry_catch() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/negative/try_catch.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/operators")
    @TestDataPath("$PROJECT_ROOT")
    public class Operators {
      @Test
      public void testAllFilesPresentInOperators() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/operators"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("basic.kt")
      public void testBasic() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/operators/basic.kt");
      }

      @Test
      @TestMetadata("elvis.kt")
      public void testElvis() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/operators/elvis.kt");
      }

      @Test
      @TestMetadata("identity_equality.kt")
      public void testIdentity_equality() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/operators/identity_equality.kt");
      }

      @Test
      @TestMetadata("safe_call.kt")
      public void testSafe_call() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/operators/safe_call.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/pure_functions")
    @TestDataPath("$PROJECT_ROOT")
    public class Pure_functions {
      @Test
      public void testAllFilesPresentInPure_functions() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/pure_functions"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("branching.kt")
      public void testBranching() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/pure_functions/branching.kt");
      }

      @Test
      @TestMetadata("heap_dependent_specifications.kt")
      public void testHeap_dependent_specifications() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/pure_functions/heap_dependent_specifications.kt");
      }

      @Test
      @TestMetadata("literal_returns.kt")
      public void testLiteral_returns() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/pure_functions/literal_returns.kt");
      }

      @Test
      @TestMetadata("local_variables.kt")
      public void testLocal_variables() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/pure_functions/local_variables.kt");
      }

      @Test
      @TestMetadata("operators.kt")
      public void testOperators() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/pure_functions/operators.kt");
      }

      @Test
      @TestMetadata("pure_callee_error_once.kt")
      public void testPure_callee_error_once() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/pure_functions/pure_callee_error_once.kt");
      }

      @Test
      @TestMetadata("pure_function_with_heap_dependent_expressions.kt")
      public void testPure_function_with_heap_dependent_expressions() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/pure_functions/pure_function_with_heap_dependent_expressions.kt");
      }

      @Test
      @TestMetadata("pure_open.kt")
      public void testPure_open() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/pure_functions/pure_open.kt");
      }

      @Test
      @TestMetadata("unique_receivers.kt")
      public void testUnique_receivers() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/pure_functions/unique_receivers.kt");
      }

      @Test
      @TestMetadata("unique_recursion.kt")
      public void testUnique_recursion() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/pure_functions/unique_recursion.kt");
      }

      @Test
      @TestMetadata("unique_tree_recursion.kt")
      public void testUnique_tree_recursion() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/pure_functions/unique_tree_recursion.kt");
      }

      @Test
      @TestMetadata("var_reads_without_unique.kt")
      public void testVar_reads_without_unique() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/pure_functions/var_reads_without_unique.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/purity")
    @TestDataPath("$PROJECT_ROOT")
    public class Purity {
      @Test
      public void testAllFilesPresentInPurity() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/purity"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("assert_statements.kt")
      public void testAssert_statements() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/purity/assert_statements.kt");
      }

      @Test
      @TestMetadata("wrongly_annotated.kt")
      public void testWrongly_annotated() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/purity/wrongly_annotated.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/types")
    @TestDataPath("$PROJECT_ROOT")
    public class Types {
      @Test
      public void testAllFilesPresentInTypes() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/types"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("any.kt")
      public void testAny() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/types/any.kt");
      }

      @Test
      @TestMetadata("casts.kt")
      public void testCasts() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/types/casts.kt");
      }

      @Test
      @TestMetadata("enums.kt")
      public void testEnums() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/types/enums.kt");
      }

      @Test
      @TestMetadata("generics.kt")
      public void testGenerics() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/types/generics.kt");
      }

      @Test
      @TestMetadata("multiset_errors.kt")
      public void testMultiset_errors() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/types/multiset_errors.kt");
      }

      @Test
      @TestMetadata("nullable.kt")
      public void testNullable() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/types/nullable.kt");
      }
    }

    @Nested
    @TestMetadata("formver.compiler-plugin/testData/diagnostics/verification/user_invariants")
    @TestDataPath("$PROJECT_ROOT")
    public class User_invariants {
      @Test
      public void testAllFilesPresentInUser_invariants() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/testData/diagnostics/verification/user_invariants"), Pattern.compile("^(.+)\\.kt$"), null, true);
      }

      @Test
      @TestMetadata("and_or_then.kt")
      public void testAnd_or_then() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/and_or_then.kt");
      }

      @Test
      @TestMetadata("conditional_specifications.kt")
      public void testConditional_specifications() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/conditional_specifications.kt");
      }

      @Test
      @TestMetadata("derived_triggers.kt")
      public void testDerived_triggers() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/derived_triggers.kt");
      }

      @Test
      @TestMetadata("empty.kt")
      public void testEmpty() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/empty.kt");
      }

      @Test
      @TestMetadata("exists.kt")
      public void testExists() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/exists.kt");
      }

      @Test
      @TestMetadata("exists_list_get_crash.kt")
      public void testExists_list_get_crash() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/exists_list_get_crash.kt");
      }

      @Test
      @TestMetadata("factorial.kt")
      public void testFactorial() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/factorial.kt");
      }

      @Test
      @TestMetadata("forall_with_triggers.kt")
      public void testForall_with_triggers() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/forall_with_triggers.kt");
      }

      @Test
      @TestMetadata("loops.kt")
      public void testLoops() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/loops.kt");
      }

      @Test
      @TestMetadata("simple_forall.kt")
      public void testSimple_forall() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/simple_forall.kt");
      }

      @Test
      @TestMetadata("simple_postcondition.kt")
      public void testSimple_postcondition() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/simple_postcondition.kt");
      }

      @Test
      @TestMetadata("simple_precondition.kt")
      public void testSimple_precondition() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/simple_precondition.kt");
      }

      @Test
      @TestMetadata("string_iterations.kt")
      public void testString_iterations() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/string_iterations.kt");
      }

      @Test
      @TestMetadata("strings_in_conditions.kt")
      public void testStrings_in_conditions() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/strings_in_conditions.kt");
      }

      @Test
      @TestMetadata("sum_of_1_to_n.kt")
      public void testSum_of_1_to_n() {
        runTest("formver.compiler-plugin/testData/diagnostics/verification/user_invariants/sum_of_1_to_n.kt");
      }
    }
  }
}
