

package org.jetbrains.kotlin.formver.plugin.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.formver.plugin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("formver.compiler-plugin/locality/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class LocalityDiagnosticTestGenerated extends AbstractLocalityDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/locality/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("assign_local.kt")
  public void testAssign_local() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/assign_local.kt");
  }

  @Test
  @TestMetadata("assign_property.kt")
  public void testAssign_property() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/assign_property.kt");
  }

  @Test
  @TestMetadata("buffer_builder.kt")
  public void testBuffer_builder() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/buffer_builder.kt");
  }

  @Test
  @TestMetadata("call.kt")
  public void testCall() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/call.kt");
  }

  @Test
  @TestMetadata("call_anonymous.kt")
  public void testCall_anonymous() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/call_anonymous.kt");
  }

  @Test
  @TestMetadata("call_with_context.kt")
  public void testCall_with_context() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/call_with_context.kt");
  }

  @Test
  @TestMetadata("call_with_vararg.kt")
  public void testCall_with_vararg() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/call_with_vararg.kt");
  }

  @Test
  @TestMetadata("cast.kt")
  public void testCast() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/cast.kt");
  }

  @Test
  @TestMetadata("closure_capture.kt")
  public void testClosure_capture() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/closure_capture.kt");
  }

  @Test
  @TestMetadata("conditional_expression.kt")
  public void testConditional_expression() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/conditional_expression.kt");
  }

  @Test
  @TestMetadata("connection_pool.kt")
  public void testConnection_pool() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/connection_pool.kt");
  }

  @Test
  @TestMetadata("construction_receiver.kt")
  public void testConstruction_receiver() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/construction_receiver.kt");
  }

  @Test
  @TestMetadata("constructor.kt")
  public void testConstructor() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/constructor.kt");
  }

  @Test
  @TestMetadata("default_argument.kt")
  public void testDefault_argument() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/default_argument.kt");
  }

  @Test
  @TestMetadata("deferred_callbacks.kt")
  public void testDeferred_callbacks() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/deferred_callbacks.kt");
  }

  @Test
  @TestMetadata("inner_function.kt")
  public void testInner_function() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/inner_function.kt");
  }

  @Test
  @TestMetadata("invalid.kt")
  public void testInvalid() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/invalid.kt");
  }

  @Test
  @TestMetadata("pure_call.kt")
  public void testPure_call() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/pure_call.kt");
  }

  @Test
  @TestMetadata("return.kt")
  public void testReturn() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/return.kt");
  }

  @Test
  @TestMetadata("specification.kt")
  public void testSpecification() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/specification.kt");
  }

  @Test
  @TestMetadata("throw.kt")
  public void testThrow() {
    runTest("formver.compiler-plugin/locality/testData/diagnostics/throw.kt");
  }

  @Nested
  @TestMetadata("formver.compiler-plugin/locality/testData/diagnostics/contract")
  @TestDataPath("$PROJECT_ROOT")
  public class Contract {
    @Test
    public void testAllFilesPresentInContract() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("formver.compiler-plugin/locality/testData/diagnostics/contract"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("assign_local.kt")
    public void testAssign_local() {
      runTest("formver.compiler-plugin/locality/testData/diagnostics/contract/assign_local.kt");
    }

    @Test
    @TestMetadata("call.kt")
    public void testCall() {
      runTest("formver.compiler-plugin/locality/testData/diagnostics/contract/call.kt");
    }

    @Test
    @TestMetadata("call_anonymous.kt")
    public void testCall_anonymous() {
      runTest("formver.compiler-plugin/locality/testData/diagnostics/contract/call_anonymous.kt");
    }

    @Test
    @TestMetadata("call_with_context.kt")
    public void testCall_with_context() {
      runTest("formver.compiler-plugin/locality/testData/diagnostics/contract/call_with_context.kt");
    }

    @Test
    @TestMetadata("call_with_vararg.kt")
    public void testCall_with_vararg() {
      runTest("formver.compiler-plugin/locality/testData/diagnostics/contract/call_with_vararg.kt");
    }

    @Test
    @TestMetadata("conditional_expression.kt")
    public void testConditional_expression() {
      runTest("formver.compiler-plugin/locality/testData/diagnostics/contract/conditional_expression.kt");
    }

    @Test
    @TestMetadata("default_argument.kt")
    public void testDefault_argument() {
      runTest("formver.compiler-plugin/locality/testData/diagnostics/contract/default_argument.kt");
    }

    @Test
    @TestMetadata("pass_function_reference.kt")
    public void testPass_function_reference() {
      runTest("formver.compiler-plugin/locality/testData/diagnostics/contract/pass_function_reference.kt");
    }

    @Test
    @TestMetadata("return.kt")
    public void testReturn() {
      runTest("formver.compiler-plugin/locality/testData/diagnostics/contract/return.kt");
    }
  }
}
